### ISSUE TITLE
unable to run lvm2qcow2.py on CentOS 6.7

### ISSUE THREAD

**Issue by dark-vex** [lucagiove/lvm2qcow2#1]
[root@srv]# ./lvm2qcow2.py -s /dev/VolGroup/Firewall -d /mnt/backup/Backup-Hypervisor/Firewall -n 5
Traceback (most recent call last):
  File "./lvm2qcow2.py", line 235, in <module>
    main()
  File "./lvm2qcow2.py", line 193, in main
    version="%(prog)s {}".format(**version**))
ValueError: zero length field name in format

It seems due to the python version
http://stackoverflow.com/questions/5446964/valueerror-zero-length-field-name-in-format-error-in-python-3-0-3-1-3-2

**Comment by dark-vex** [comment]
Close this I have added some extra steps in the README file for CentOS, see:
https://github.com/lucagiove/lvm2qcow2/pull/2
